version: '3.4'

services:
  chat.api:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: .
      dockerfile: Chat/Dockerfile
    depends_on:
       - postgresdb
    networks:
       - chat-network

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    volumes:
       - pgdata:/var/lib/postgresql/data
    networks:
       - chat-network

networks:
    chat-network:
        driver: bridge

volumes:
    pgdata: